---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01-vulnerability-scanning
      label: "Vulnerability Scanning Container Images"
      solveButton: false
    - name: module-02-sbom-generation
      label: "Working with SBOMs"
      solveButton: false
    - name: module-03-verifying-signatures
      label: "Verifying Published Signatures"
      solveButton: false
    - name: module-04-signing-setup
      label: "Image Signing Setup (Push and Generate Keys)"
      solveButton: false
    - name: module-05-signing-verification
      label: "Image Signing and Verification"
      solveButton: false
    - name: module-06-sbom-attestation
      label: "Image SBOM Attestation"
      solveButton: false
    - name: module-07-supply-chain-trust
      label: "Establishing Supply Chain Trust"
      solveButton: false

tabs:
  - name: ">_ terminal"
    path: /wetty

